# Generated by Django 2.2.26 on 2022-07-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dividends_drip_holdingvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.BigIntegerField()),
                ('date', models.DateField()),
                ('symbolId', models.BigIntegerField()),
                ('closePrice', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
        ),
        migrations.RenameField(
            model_name='holdingvalue',
            old_name='holdId',
            new_name='uniqueId',
        ),
        migrations.AddField(
            model_name='dividends',
            name='uniqueId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drip',
            name='uniqueId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
